name: flutter_video_call_demo
description: A new Flutter application.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  flutter_launcher_icons: ^0.11.0
  shimmer: ^2.0.0
  image_picker: ^0.7.2+1
  video_player: ^2.4.10
  intl: ^0.18.0
  firebase_core: ^2.4.0
  stop_watch_timer: ^2.0.0
  assets_audio_player: ^3.0.6
  audioplayers: ^1.1.1
  fluttertoast: ^8.1.2
  lottie: ^2.2.0
  agora_rtc_engine: ^5.3.0
  permission_handler: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
    - assets/

